services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.4
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://text2vec-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  text2vec-transformers:
    # Check the list of supported images --> https://docs.weaviate.io/weaviate/model-providers/transformers/embeddings#available-models
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: "0"   # set to "1" if you want GPU
      # NVIDIA_VISIBLE_DEVICES: all  # uncomment if using GPU
    restart: on-failure:0

volumes:
  weaviate_data:
