datasets_dir = "/home/nmarques/project/finetuning/gervasio-datasets"
datasets_cache_dir = "/home/nmarques/project/finetuning/gervasio-datasets/cache"
datasets_aliases = ["ptwikirag"]
batch_max_examples = 1800
batch_max_tokens = 2048
base_model_name = "/home/nmarques/project/finetuning/gervasio/models/3b_models/best-3B-model/gervasio-3b-403-alpha128-merged"
# adapter_name = "..."
output_dir = "/home/nmarques/project/ft2/gervasio/models/3b_models/gervasio-3b-0388803"
full_finetuning = false
lora_r = 8
lora_alpha = 32
lr = 0.00001
lr_gamma = 0.85
warmup_steps = 500
num_epochs = 10
num_epoch_checkpoints = 1
hourly_checkpoint = true
auto_resume = true
weight_decay = 0.01
seed = 1234
enable_gradient_checkpointing = false
enable_fsdp = false
run_eval = false
verbose = true
quiet_higher_ranks = true

[datasets_configs]
ptwikirag = {}